<a href="https://colab.research.google.com/github/yogananda26/Mechine_Learning/blob/master/Learning_MechineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [193]:
# this is for importing the thing
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
print("success")

success


1. Learing thing

In [194]:
#this is for inserting the csv file from web
!wget "https://raw.githubusercontent.com/yogananda26/Mechine_Learning/master/weatherAUS.csv/weatherAUS.csv"
df = pd.read_csv("weatherAUS.csv")
# this is for printing the data
df.describe

--2023-11-04 07:43:45--  https://raw.githubusercontent.com/yogananda26/Mechine_Learning/master/weatherAUS.csv/weatherAUS.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14094055 (13M) [text/plain]
Saving to: ‘weatherAUS.csv.6’

weatherAUS.csv.6    100%[===================>]  13.44M  --.-KB/s    in 0.04s   

2023-11-04 07:43:45 (341 MB/s) - ‘weatherAUS.csv.6’ saved [14094055/14094055]



<bound method NDFrame.describe of               Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          NaN   
1       2008-12-02   Albury      7.4     25.1       0.0          NaN   
2       2008-12-03   Albury     12.9     25.7       0.0          NaN   
3       2008-12-04   Albury      9.2     28.0       0.0          NaN   
4       2008-12-05   Albury     17.5     32.3       1.0          NaN   
...            ...      ...      ...      ...       ...          ...   
145455  2017-06-21    Uluru      2.8     23.4       0.0          NaN   
145456  2017-06-22    Uluru      3.6     25.3       0.0          NaN   
145457  2017-06-23    Uluru      5.4     26.9       0.0          NaN   
145458  2017-06-24    Uluru      7.8     27.0       0.0          NaN   
145459  2017-06-25    Uluru     14.9      NaN       0.0          NaN   

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  \
0            NaN          

In [195]:
# this is for starting the mechine learning
X = df.iloc[: , [1,2,3,4,7,8,9,10,11,12,13,15,16,17,18,19,20,21]].values
Y = df.iloc[: , -1].values
Y = Y.reshape(-1, 1)

print(X)
# this is for output
print("this is for output")
print(Y)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 nan ... 15.0 20.9 'No']]
this is for output
[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 [nan]]


This is for dealing with invalid data set

In [196]:

# this is for filling the dataset wether the dataset had nan value
imp_most_frequent = SimpleImputer(missing_values=np.nan, strategy="most_frequent")
X = imp_most_frequent.fit_transform(X)
Y = imp_most_frequent.fit_transform(Y)
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


this is for translate the text into number for simple processing


In [197]:
# this is for changing the coloumn
fit0 = LabelEncoder()
X[: , 0] = fit0.fit_transform(X[:,0])
fit = LabelEncoder()
X[: , 4] = fit.fit_transform(X[:,4])
fit1 = LabelEncoder()
X[: ,6] = fit.fit_transform(X[: , 6])
fit2 = LabelEncoder()
X[: , 7] = fit2.fit_transform(X[:,7])
fit3 = LabelEncoder()
X[: , -1] = fit3.fit_transform(X[:,-1])

# this is for changing the graph Y
fit_y = LabelEncoder()
Y = fit_y.fit_transform(Y)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Featuring Scalling

In [198]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
print(X)

[[-1.53166617  0.19132753 -0.04135977 ... -0.01407077  0.02310362
  -0.52979545]
 [-1.53166617 -0.75105231  0.26874452 ...  0.03244663  0.387799
  -0.52979545]
 [-1.53166617  0.11279588  0.35331842 ...  0.62166712  0.22733303
  -0.52979545]
 ...
 [ 1.20928479 -1.06517892  0.52246622 ... -0.69632607  0.65037966
  -0.52979545]
 [ 1.20928479 -0.68822699  0.53656187 ... -0.29317521  0.63579185
  -0.52979545]
 [ 1.20928479  0.42692249 -0.45013361 ... -0.30868102 -0.10818671
  -0.52979545]]


Splitting Training And Testing Model (more training you have better result youll get)

In [199]:
# this is for spliting the data into testing and training test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.8, random_state=0)

print(X_train)
print("=====================")
print(X_test)
print("=====================")
print(Y_train)
print("=====================")
print(Y_test)


[[ 0.0145113   0.25415285 -0.83071616 ... -0.38621003 -0.23947704
   1.88752093]
 [ 1.139004   -0.21703707  0.35331842 ... -0.1846346   0.30027211
  -0.52979545]
 [ 0.85788082 -1.89761445 -1.0421509  ... -1.37858137 -0.92510434
  -0.52979545]
 ...
 [ 1.0687232   0.75675544  0.93124006 ...  1.10234698  1.07342629
  -0.52979545]
 [ 0.57675765 -0.04426743 -0.16822062 ...  0.01694083 -0.28324049
   1.88752093]
 [ 1.63096955 -0.0285611  -0.91529006 ... -0.35519842 -0.76463838
  -0.52979545]]
[[-1.46138537  1.52636564  2.28442243 ...  1.98617771  2.00704644
   1.88752093]
 [ 1.27956559  1.30647701  2.01660509 ...  1.59853265  2.05080989
  -0.52979545]
 [ 0.85788082 -1.11229791 -0.84481181 ... -1.06846532 -0.80840182
  -0.52979545]
 ...
 [-0.12605029  0.23844652  1.87564859 ...  1.35043982  1.3797704
  -0.52979545]
 [-0.75857743  1.82478592  1.72059644 ...  1.83111969  1.49647292
  -0.52979545]
 [ 0.71731924  0.88240608  2.04479639 ...  0.88526575  2.1675124
  -0.52979545]]
[1 0 0 ... 0 0 0]


This for MECHINE LEARNING KICK IN

In [200]:
# this is for mechine learning
# we use randomforest classfier for predicting thing on discrete way
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0)
classifier.fit(X_train, Y_train)


RandomForestClassifier(random_state=0)

This is for Checking the data that we given is Good or Bad

In [201]:
# this is how much the tree was perfomed
classifier.score(X_train, Y_train)

0.9999656262890142

In [202]:
Y_predict = classifier.predict(X_test)

In [203]:
print(Y_predict)
print(Y_test)

[0 0 0 ... 0 0 0]
[1 1 0 ... 0 0 0]


In [204]:
Y_predict = fit_y.inverse_transform(Y_predict)
Y_test = fit_y.inverse_transform(Y_test)
# Y_predict = Y_predict.reshape(-1, 1)


In [205]:
Y_predict = Y_predict.reshape(-1,1)
Y_test = Y_test.reshape(-1,1)

In [206]:
# this is for displaying the result
func = np.concatenate((Y_test, Y_predict), axis=1)

In [211]:
df = pd.DataFrame(data=func, columns=["Tommorow Raining", "Prediction of Raining"])
print(df)

       Tommorow Raining Prediction of Raining
0                   Yes                    No
1                   Yes                    No
2                    No                    No
3                    No                    No
4                    No                    No
...                 ...                   ...
116363               No                    No
116364               No                    No
116365               No                    No
116366               No                    No
116367               No                    No

[116368 rows x 2 columns]
